Feature/botaoexportacao
brenosss/peticoes-client pull request #10
Opened 2021-01-19 11:53 UTC by chamorim21

Criei outra página onde há um input e um botão para definir o nome do template a ser exportado.

Também fiz uma pequena navbar em que pode-se alternar entre a tela de criação de variáveis e a tela de exportação do template.

2021-01-20 14:43 UTC, gasparpn commented
Sugiro que nesses PRs do front coloquemos imagens de como a tela vai ficar após o merge.

2021-01-20 14:44 UTC, gasparpn approved these changes

2021-01-27 20:49 UTC, gasparpn approved these changes

2021-01-28 14:01 UTC, brenosss commented on src/taskpane/extensao/src/pages/Exportar.js
> +    setHabilitado(e.target.value);
Se eu colocar um nome nome no template e depois apagar? o botão vai ficar ativo?

2021-01-28 14:04 UTC, brenosss commented on src/taskpane/extensao/src/App.js
> +          <Button
Faz sentido usar button aqui?
dá uma olhada aqui: https://react-bootstrap.github.io/components/navs/#tabs

2021-01-28 14:05 UTC, brenosss commented on src/taskpane/extensao/src/App.js
> +import * as React from "react";
É melhor você usar `import React, { useState } from "react";`

2021-01-28 14:06 UTC, brenosss requested changes
Deixei alguns pontos pra revisar

2021-01-28 14:41 UTC, chamorim21 commented on src/taskpane/extensao/src/pages/Exportar.js
> +    setHabilitado(e.target.value);
Uma string vazia, que é o valor inicial desse estado, é reconhecida como `false`. Existe uma propriedade `disabled` no botão que começa com o valor contrário desse estado, ou seja, `true`, assim mantendo o botão desabilitado. Dessa forma o botão manterá-se desabilitado juntamente quando o input estiver vazio, já que ao digitar no input, há a chamada da função de setar o estado para um valor, quando isso acontece, o `habilitado` passa a ser reconhecido como `true`.

Quando o input fica vazio, o botão fica desabilitado. O botão só ficará ativo a partir do momento que o input começar a ser preenchido.

2021-01-28 14:42 UTC, chamorim21 commented on src/taskpane/extensao/src/App.js
> +import * as React from "react";
Ok, entendido.

2021-01-28 15:04 UTC, chamorim21 commented on src/taskpane/extensao/src/App.js
> +          <Button
Fiz as alterações e mudei para Tab, acredito que tenha melhorado bastante, além de ter deixado o código mais sucinto, peço que dê uma olhada.

2021-02-01 15:08 UTC, brenosss commented on src/taskpane/extensao/src/pages/Exportar.js
> +    setHabilitado(e.target.value);
Tranquilo!

2021-02-01 15:09 UTC, brenosss approved these changes

2021-02-01 17:29 UTC, merged