Feature/novasvariaveis
brenosss/peticoes-client pull request #12
Opened 2021-01-20 01:06 UTC by chamorim21

Criei dois novos tipos de variáveis: decimal e numérica, em que só aceitam números no input. Também, criei novos campos como: pergunta, explicação longa e explicação curta, bem como inclui esses em campos comuns a todas as variáveis.

2021-01-20 14:56 UTC, gasparpn commented on q
> +[33mcommit d4b4de39a5b894fe50373b5557edf6e0619364f5[m[33m ([m[1;36mHEAD -> [m[1;32mfeature/novasvariaveis[m[33m)[m
Que arquivo é esse? kkkk Acredito que não era pra ter commitado.

2021-01-20 14:56 UTC, gasparpn commented on src/taskpane/extensao/src/components/FormNovaVariavel/FormNovaVariavelNumerica.js
> +export function FormNovaVariavelNumerica({ mudaNovaVariavel }) {
Não vi diferença dessa função para a `FormNovaVariavelDecimal`. Sugiro colocar ela em u hook e chamar onde for precisar, se possível.

2021-01-20 14:56 UTC, gasparpn commented on src/taskpane/extensao/src/components/FormNovaVariavel/index.js
> +import React, { useState } from "react";
O padrão que estamos usando é com aspas duplas mesmo? Pergunto porque seu lint alterou bastante o arquivo.

2021-01-20 16:18 UTC, chamorim21 commented on src/taskpane/extensao/src/components/FormNovaVariavel/index.js
> +import React, { useState } from "react";
de fato, preciso configurar meu lint.

2021-01-20 16:19 UTC, chamorim21 commented on src/taskpane/extensao/src/components/FormNovaVariavel/FormNovaVariavelNumerica.js
> +export function FormNovaVariavelNumerica({ mudaNovaVariavel }) {
entendido

2021-01-20 16:20 UTC, chamorim21 commented on q
> +[33mcommit d4b4de39a5b894fe50373b5557edf6e0619364f5[m[33m ([m[1;36mHEAD -> [m[1;32mfeature/novasvariaveis[m[33m)[m
eita, também não consegui entender de onde está vindo ... irei apagar

2021-01-21 10:51 UTC, gasparpn approved these changes

2021-01-28 14:11 UTC, brenosss requested changes

2021-01-28 14:11 UTC, brenosss commented on src/taskpane/extensao/src/components/FormNovaVariavel/FormNovaVariavelNumerica.js
> +  const mudaText = (event, campo) => {
É correto chamar isso de `mudaText`?

2021-01-28 14:11 UTC, brenosss commented on src/taskpane/extensao/src/components/FormNovaVariavel/index.js
> +const TIPOS_FORM = {
Esses tipos já estão bem grande, podemos colocar em um arquivo de tipos e importar

2021-01-28 14:11 UTC, brenosss commented on src/taskpane/extensao/src/components/FormNovaVariavel/index.js
> +function FormNovaVariavelCamposComuns({ mudaNovaVariavel, mudaTipoVariavel }) {
Veja se esse cara também pode ser extraido para outro arquivo

2021-01-28 16:29 UTC, chamorim21 commented on src/taskpane/extensao/src/components/FormNovaVariavel/FormNovaVariavelNumerica.js
> +  const mudaText = (event, campo) => {
alterado!

2021-01-28 16:39 UTC, chamorim21 commented on src/taskpane/extensao/src/components/FormNovaVariavel/index.js
> +const TIPOS_FORM = {
Feito.

2021-01-28 16:39 UTC, chamorim21 commented on src/taskpane/extensao/src/components/FormNovaVariavel/index.js
> +function FormNovaVariavelCamposComuns({ mudaNovaVariavel, mudaTipoVariavel }) {
Ok!

2021-02-01 15:11 UTC, brenosss approved these changes

2021-02-01 17:26 UTC, merged